package com.example.deckadence;

import android.util.Log;

import androidx.annotation.NonNull;

import com.example.deckadence.deck.Deck;
import com.example.deckadence.deck.Flashcard;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QueryDocumentSnapshot;
import com.google.firebase.firestore.QuerySnapshot;

import java.util.List;

public class FirebaseHelper {
    private FirebaseFirestore db;
    private String TAG = "FireStore";

    public FirebaseHelper(FirebaseFirestore db) {
        this.db = db;
    }
    // returns string array with deck title and description

    public void addDeck(Deck deck) {
        // use autogenerated ids prevent decks with the same name from sharing cards
        db.collection("Deck").document().set(deck);
        Log.d(TAG, "Added Deck");
    }
    public String[] getDeckInfo(String deckID) {
        DocumentReference deckRef = db.collection("Deck").document(deckID);
        String[] returnArray = new String[2];
        Log.d(TAG, "d");
        deckRef.get().addOnCompleteListener(new OnCompleteListener<DocumentSnapshot>() {
            @Override
            public void onComplete(@NonNull Task<DocumentSnapshot> task) {
                if (task.isSuccessful()) {
                    DocumentSnapshot document = task.getResult();
                    if (document.exists()) {
                        Log.d(TAG, "Deck exists");
                        returnArray[0] = (String) document.getData().get("title");
                        returnArray[1] = (String) document.getData().get("description");
                    } else {
                        Log.d(TAG, "No such deck");
                    }
                } else {
                    Log.d(TAG, "get failed with ", task.getException());
                }
            }
        });
        if(returnArray[0] != null) {
            return returnArray;
        } else {
            return null;
        }
    }
    public void addCard(Flashcard card, String deckID) {
        DocumentReference docRef = db.collection("Deck").document(deckID);
        docRef.get().addOnSuccessListener(new OnSuccessListener<DocumentSnapshot>() {
            @Override
            public void onSuccess(DocumentSnapshot documentSnapshot) {
                // use autogenerated ids
                db.document("Deck/" + documentSnapshot.getId()).collection("cards").document().set(card);
                Log.d(TAG, "Added Card");
            }
        });
    }

    public void getCards(String deckID) {
        // gets cards for a given deckID
        DocumentReference docRef = db.collection("Deck").document(deckID);
        docRef.get().addOnSuccessListener(new OnSuccessListener<DocumentSnapshot>() {
            @Override
            public void onSuccess(DocumentSnapshot documentSnapshot) {
                // for the deck, access the subcollection 'cards'
                db.document("Deck/" + documentSnapshot.getId()).collection("cards").get().addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                        @Override
                        public void onSuccess(QuerySnapshot queryDocumentSnapshots) {
                            for (QueryDocumentSnapshot qs: queryDocumentSnapshots
                            ) {
                                Log.d("DEBUG", qs.toString());
                            }
                        }
                    });
            }
        });


    }
}
